### ISSUE TITLE
Improve user tracking when user is far away from the Kinect

### ISSUE THREAD

**Issue by mloo3** [cclaassen3/augmented_climbing#29]

**Comment by cclaassen3** [comment]
changing the title from allot time to modify game based on user feedback from testing --> Improve user tracking when user is far away from the Kinect, as this was the main takeaway from the user testing performed at the CRC on 03/29

**Comment by cclaassen3** [comment]
tracking improved a bit, but not perfect. limitations not due to our own algorithm, so accepting it as is.
